<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../src/Types.fs" />
    <Compile Include="../src/CodeAnalysis.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
